apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.Deployment.name }}
spec:
  replicas: {{ .Values.Deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.name }}
    spec:
      containers:
        - name: {{ .Values.Deployment.name }}
          image: {{ .Values.Deployment.image.name }}:{{ .Values.Deployment.image.tag }}
          resources:
            requests:
              cpu: {{ .Values.Deployment.resources.requests.cpu }}
              memory: {{ .Values.Deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.Deployment.resources.limits.cpu }}
              memory: {{ .Values.Deployment.resources.limits.memory }}
            livenessProbe:
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 3
              httpGet:
                path: "/live"
                port: 8080
            readinessProbe:
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3
              httpGet:
                path: "/ready"
                port: 8080