services:
  Nginx:
    ports:
      - "8080:80"
    networks:
      - public-net-1
    volumes:
      - /data/nginx:/etc/nginx/conf.d
    image: nginx

  NetflixFrontend:
    environment:
      MOVIE_CATALOG_SERVICE: http://NetflixMovieCatalog:8080
    networks:
      - public-net-1
      - private-net-1
    image: ofekhalabi/netflix-frontend

  NetflixMovieCatalog:
    networks:
      - private-net-1
    image: ofekhalabi/netflix-movie-catalog

  Availabilityagent:
    environment:
      MONITORED_HOST: http://Nginx:80
    networks:
      - private-net-2
      - public-net-1
    image: ofekhalabi/availability_agent:1.0.0

  Grafana:
    ports:
      - "3000:3000"
    networks:
      - private-net-2
    volumes:
      - /data/grafana:/var/lib/grafana
    image: grafana/grafana


  Prometheus:
    networks:
      - private-net-2
    volumes:
      - /data/prometheus/files/prometheus.yaml:/etc/prometheus/prometheus.yml
      - /data/prometheus:/prometheus
    image: prom/prometheus

networks:
  public-net-1:
    driver: bridge
  private-net-1:
    driver: bridge
  private-net-2:
    driver: bridge
