---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: server
          image: grafana/grafana:latest
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 50m
              memory: 150Mi
            livenessProbe:
              initialDelaySeconds: 10
              httpGet:
                path: "/api/health" # Grafana health check endpoint
                port: 3000
            readinessProbe:
              initialDelaySeconds: 10
              httpGet:
                path: "/api/health" # Grafana readiness check endpoint
                port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000

