---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
    - hosts:
      - ofekhnetflix.dev.devops-int-college.com # change this URL
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for ofekhnetflix.devops-int-college.com
      secretName: tls-secret
  ingressClassName: nginx
  rules:
    - host: ofekhnetflix.devops-int-college.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: netflix-frontend-service-dev
              port:
                number: 3000

